### ISSUE TITLE
nostr-sdk update caused error?

### ISSUE THREAD

**Issue by davidtseng** [reyamir/sentinel#2]
I had been running sentinel and then last night started getting this error.

TypeError: undefined is not an object (evaluating 'arg.length')
at passStringToWasm0 (..node_modules/@rust-nostr/nostr-sdk/pkg/nostr_sdk_js.js:70:15)
       at ../node_modules/@rust-nostr/nostr-sdk/pkg/nostr_sdk_js.js:5836:18
...

Re-install sees same error.

**Comment by reyamir** [comment]
oh, let me check it, maybe related to latest rust-nostr update

**Comment by reyamir** [comment]
Hi, I've found the problem, if feed's content is not found by this code
```
let content: string = item.summary || item.description || item.title
```

sentinel will crash. I've fixed it by make sure content always exist (empty string instead of undefined)
```
let content: string = item.summary || item.description || item.title || "";
```

**Comment by reyamir** [comment]
I've pushed new update, can you help me verify it on your side?

**Comment by davidtseng** [comment]
I just tested a re-install and I'm still getting the same error. Does your feed work fine? Must be something on my end, I'll keep looking.

**Comment by davidtseng** [comment]
@reyamir Investigated the error a bit, seems to be if 'reason' is undefined. I'm not too familiar but it looks like the reason may be part of the new nip-46 which was recently introduced. The versions in package.json are specific and older so I don't know how this would get introduced. All a bit new to me!

**Comment by reyamir** [comment]
Oh, let me test it more
